### PR TITLE
#19: On click anywhere plays a paused story

### PR DESCRIPTION
**Pull request by meetbhalodi11**
## Describe your changes
1, **onRelease** function was being called all the time even if the story was not put on hold. so added a check there such that this function will be called only if the story was on hold.
2, storyState changed to playing when story was out of hold (to change the icon of play and pause button)

## Issue ticket number and link
#19 

## Checklist before requesting a review

- [o] I have performed a self-review of my code.

- [o] Followed the repository's [Contributing Guidelines](https://github.com/Gauravdarkslayer/ngx-stories/blob/main/CONTRIBUTING.md).

- [o] I ran the app and tested it locally to verify that it works as expected.

- [o] I have starred the repository.

### CODE REVIEW

**Comment by Gauravdarkslayer** [comment]
Hi @meetbhalodi11 ,
I've checked your code, but seems like the problem still persists,
Pause the story using pause button, and click anywhere on the story, you will notice that the story again starts playing.

**Comment by meetbhalodi11** [comment]
@Gauravdarkslayer The main issue is resolved however the issue you are mentioning is due that is because of the handleSwipe left/right. let me fix that too

**Comment by Gauravdarkslayer** [comment]
@meetbhalodi11 Yes it can be.
Thank you!

**Comment by meetbhalodi11** [comment]
@Gauravdarkslayer 
Current Behaviour: when user click on the right side of the story it navigates to the next story and similarly if user click on the left side it navigates to the previous story. Even if the story is paused this things will happen

Question: What is exactly not suppose to happen in this case? Is it that we don't want to play the story when user navigates through the stories when the story is paused?

**Comment by Gauravdarkslayer** [comment]
@meetbhalodi11 , So basically the plan is to disable next and previous buttons (hidden buttons) only on desktop view. 
And for user convenience we'll add arrow button navigation on desktop view, also those arrow buttons will be hidden in mobile view.
So as you've noticed that play/pause button is not visible in mobile view, but user is still able to pause the story using long mouse tap, so i'll open a new issue mentioning what to enable in mobile view and what to disable in desktop view.
By the way this behaviour is visible in instagram stories as well. on desktop view they are enabling arrow button navigation.
If you want to discuss more, then here's my discord id, let's catch up there `gauravdarkslayer` .

**Review by Gauravdarkslayer — APPROVED** [review]

**Pull request merged**
